// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/10/2025, 6:59:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/bartek/Projects/home-cost-analyzer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/plugins/**/*.{js,ts,mjs}","/Users/bartek/Projects/home-cost-analyzer/app/composables/**/*.{js,ts,mjs}","/Users/bartek/Projects/home-cost-analyzer/app/utils/**/*.{js,ts,mjs}","/Users/bartek/Projects/home-cost-analyzer/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bartek/Projects/home-cost-analyzer/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;